spring.application.name=chronix
spring.datasource.url=jdbc:postgresql://localhost:5432/chronix
spring.datasource.username=postgres
spring.datasource.password=Divyansh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Chronix Worker Pool Configuration
chronix.executor.core-pool-size=3
chronix.executor.max-pool-size=5
chronix.executor.queue-capacity=100